### PR TITLE
difftime `wilcox.test()` update

### LINKED ISSUE #880: add_p() doesn't work for difftime values
---

Hi!

I have detected that add_p() doesn't work with columns of class difftime. As a matter of fact it is related with wilcox.test() which doesn't accept that class, but if the variable is parsed to numeric class with as.numeric() before using it on gtsummary workflow, it does work. 

So my suggestion is that add_p() should check if variables are of difftime class and in that case parse them with as.numeric() before inputting them into wilcox.test().

PS: t.test() does accept difftime objects

This issue is somewhat related with (#343).

Thanks in advance!

(Sorry for the horrible reprex which is rendered with the html code included, but at least the tables are rendered)

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
library(gtsummary)

set.seed(123)

time_diff <- lubridate::as.difftime(rnorm(250, 2000, 100), units = "mins")
group_sample <- sample(c("A", "B"), 250, replace = TRUE)

df <- data.frame(group_sample, time_diff)

df %>% select(group_sample, time_diff) %>% 
  tbl_summary(by=group_sample) %>% add_p()
#> There was an error in 'add_p()/add_difference()' for variable 'time_diff', p-value omitted:
#> Error in wilcox.test.default(x = structure(c(2012.92877351609, 2171.50649868833, : 'x' must be numeric
```

<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#zqwufjmfih .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zqwufjmfih .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zqwufjmfih .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zqwufjmfih .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zqwufjmfih .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zqwufjmfih .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zqwufjmfih .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zqwufjmfih .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zqwufjmfih .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zqwufjmfih .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zqwufjmfih .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zqwufjmfih .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#zqwufjmfih .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zqwufjmfih .gt_from_md > :first-child {
  margin-top: 0;
}

#zqwufjmfih .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zqwufjmfih .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zqwufjmfih .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#zqwufjmfih .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zqwufjmfih .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#zqwufjmfih .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zqwufjmfih .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zqwufjmfih .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zqwufjmfih .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zqwufjmfih .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zqwufjmfih .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#zqwufjmfih .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zqwufjmfih .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#zqwufjmfih .gt_left {
  text-align: left;
}

#zqwufjmfih .gt_center {
  text-align: center;
}

#zqwufjmfih .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zqwufjmfih .gt_font_normal {
  font-weight: normal;
}

#zqwufjmfih .gt_font_bold {
  font-weight: bold;
}

#zqwufjmfih .gt_font_italic {
  font-style: italic;
}

#zqwufjmfih .gt_super {
  font-size: 65%;
}

#zqwufjmfih .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="zqwufjmfih" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>A</strong>, N = 118<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>B</strong>, N = 132<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">time_diff</td>
<td class="gt_row gt_center">1,992 (1,934, 2,063)</td>
<td class="gt_row gt_center">1,981 (1,938, 2,055)</td>
<td class="gt_row gt_center"></td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Median (IQR)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>

class(df$time_diff)
#> [1] "difftime"

t.test(df$time_diff~df$group_sample)
#> 
#>  Welch Two Sample t-test
#> 
#> data:  df$time_diff by df$group_sample
#> t = 0.38027 mins, df = 237.43, p-value = 0.7041 mins
#> alternative hypothesis: true difference in means is not equal to 0
#> 95 percent confidence interval:
#>  -19.11303 mins  28.25683 mins
#> sample estimates:
#> Time differences in mins
#> mean in group A mean in group B 
#>        2001.558        1996.986

wilcox.test(df$time_diff~df$group_sample)
#> Error in wilcox.test.default(x = structure(c(2012.92877351609, 2171.50649868833, : 'x' must be numeric

df$time_diff <- as.numeric(df$time_diff)

df %>% select(group_sample, time_diff) %>% 
  tbl_summary(by=group_sample) %>% add_p()
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#apvbhnlzhi .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#apvbhnlzhi .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#apvbhnlzhi .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#apvbhnlzhi .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#apvbhnlzhi .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#apvbhnlzhi .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#apvbhnlzhi .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#apvbhnlzhi .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#apvbhnlzhi .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#apvbhnlzhi .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#apvbhnlzhi .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#apvbhnlzhi .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#apvbhnlzhi .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#apvbhnlzhi .gt_from_md > :first-child {
  margin-top: 0;
}

#apvbhnlzhi .gt_from_md > :last-child {
  margin-bottom: 0;
}

#apvbhnlzhi .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#apvbhnlzhi .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#apvbhnlzhi .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#apvbhnlzhi .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#apvbhnlzhi .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#apvbhnlzhi .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#apvbhnlzhi .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#apvbhnlzhi .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#apvbhnlzhi .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#apvbhnlzhi .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#apvbhnlzhi .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#apvbhnlzhi .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#apvbhnlzhi .gt_left {
  text-align: left;
}

#apvbhnlzhi .gt_center {
  text-align: center;
}

#apvbhnlzhi .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#apvbhnlzhi .gt_font_normal {
  font-weight: normal;
}

#apvbhnlzhi .gt_font_bold {
  font-weight: bold;
}

#apvbhnlzhi .gt_font_italic {
  font-style: italic;
}

#apvbhnlzhi .gt_super {
  font-size: 65%;
}

#apvbhnlzhi .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="apvbhnlzhi" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>A</strong>, N = 118<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>B</strong>, N = 132<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong><sup class="gt_footnote_marks">2</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">time_diff</td>
<td class="gt_row gt_center">1,992 (1,934, 2,063)</td>
<td class="gt_row gt_center">1,981 (1,938, 2,055)</td>
<td class="gt_row gt_center">0.9</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Median (IQR)
          <br />
        </p>
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>2</em>
          </sup>
           
          Wilcoxon rank sum test
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table></div>

<sup>Created on 2021-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
```

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
* Variables are converted to numeric before being passed to `wilcox.test()` in `add_p()` (#880)

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #880

--------------------------------------------------------------------------------

Checklist for PR reviewer

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If an update was made to `tbl_summary()`, was the same change implemented for `tbl_svysummary()`?
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `covr::report()`. Before you run, set `Sys.setenv(NOT_CRAN="true")` and begin in a fresh R session without any packages loaded. 
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update NEWS.md with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parantheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

File: R/utils-add_p_tests.R [hunk 1]
```diff
@@ -27,7 +27,7 @@ add_p_test_kruskal.test <- function(data, variable, by, ...) {
```
Comment (oranwutang) [inline R/utils-add_p_tests.R:27]: This is OK but as.numeric() should be added to the paired version of wilcox.test(), in the definition of add_p_tbl_summary_paired.wilcox.test(). I have tried to do it from rstudio but I don't know how to push to this branch (someday I'll learn how to use git)

File: data-raw/gtsummary_tests.csv [hunk 2]
```diff
@@ -2,7 +2,7 @@ class,add_p,add_difference,diff_statistic,test_package,test_name,test_fun,fun_to
 tbl_summary,TRUE,TRUE,mean difference,stats,t.test,stats::t.test,gtsummary:::add_p_test_t.test,TRUE,"t.test(variable ~ as.factor(by), data = data, conf.level = 0.95, ...)",t-test
 tbl_summary,TRUE,FALSE,,stats,aov,stats::aov,gtsummary:::add_p_test_aov,FALSE,"aov(variable ~ as.factor(by), data = data) %>% summary()",One-way ANOVA
 tbl_summary,TRUE,FALSE,,stats,kruskal.test,stats::kruskal.test,gtsummary:::add_p_test_kruskal.test,FALSE,"kruskal.test(data[[variable]], as.factor(data[[by]]))",Kruskal-Wallis test
```
Comment (oranwutang) [inline data-raw/gtsummary_tests.csv:4]: as.numeric() should be added to the vars in the paired version of wilcox.test()

**Comment by ddsjoberg** [comment]
@oranwutang good catch about the paired variant! can you test the paired version before approving?

**Comment by oranwutang** [comment]
Of course! 
Here it is: 

**Spoiler**: It works!

``` r
library(gtsummary)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

trial$difftimevar <- lubridate::as.difftime(rnorm(nrow(trial), 2000, 200), units = "mins")

trial_paired <-
  trial %>%
  select(trt, difftimevar) %>%
  group_by(trt) %>%
  mutate(id = row_number()) %>%
  ungroup()


trial_paired %>%
  filter(!is.na(difftimevar)) %>%
  group_by(id) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  tbl_summary(by = trt, include = -id) %>%
  add_p(test = difftimevar ~ "paired.wilcox.test", group = id) %>% 
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Drug A</strong>, N = 98</th>
<th style="text-align: left;"><strong>Drug B</strong>, N = 98</th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">difftimevar</td>
<td style="text-align: left;">1,994 (1,902, 2,135)</td>
<td style="text-align: left;">2,005 (1,860, 2,175)</td>
<td style="text-align: left;">0.8</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.5 (2021-03-31)
#>  os       Ubuntu 20.04.2 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Madrid               
#>  date     2021-04-29                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package       * version    date       lib source                              
#>  assertthat      0.2.1      2019-03-21 [1] CRAN (R 4.0.3)                      
#>  backports       1.2.1      2020-12-09 [1] CRAN (R 4.0.3)                      
#>  broom           0.7.6      2021-04-05 [1] CRAN (R 4.0.5)                      
#>  broom.helpers   1.3.0      2021-04-10 [1] CRAN (R 4.0.5)                      
#>  cachem          1.0.4      2021-02-13 [1] CRAN (R 4.0.4)                      
#>  callr           3.5.1      2020-10-13 [1] CRAN (R 4.0.3)                      
#>  cli             2.3.1      2021-02-23 [1] CRAN (R 4.0.4)                      
#>  colorspace      2.0-0      2020-11-11 [1] CRAN (R 4.0.3)                      
#>  crayon          1.4.1      2021-02-08 [1] CRAN (R 4.0.4)                      
#>  DBI             1.1.1      2021-01-15 [1] CRAN (R 4.0.3)                      
#>  desc            1.2.0      2018-05-01 [1] CRAN (R 4.0.3)                      
#>  devtools        2.3.2      2020-09-18 [1] CRAN (R 4.0.4)                      
#>  digest          0.6.27     2020-10-24 [1] CRAN (R 4.0.3)                      
#>  dplyr         * 1.0.5      2021-03-05 [1] standard (@1.0.5)                   
#>  ellipsis        0.3.1      2020-05-15 [1] CRAN (R 4.0.3)                      
#>  evaluate        0.14       2019-05-28 [1] CRAN (R 4.0.3)                      
#>  fansi           0.4.2      2021-01-15 [1] CRAN (R 4.0.3)                      
#>  fastmap         1.1.0      2021-01-25 [1] CRAN (R 4.0.3)                      
#>  forcats         0.5.1      2021-01-27 [1] standard (@0.5.1)                   
#>  fs              1.5.0      2020-07-31 [1] CRAN (R 4.0.3)                      
#>  generics        0.1.0      2020-10-31 [1] CRAN (R 4.0.3)                      
#>  ggplot2         3.3.3      2020-12-30 [1] CRAN (R 4.0.3)                      
#>  glue            1.4.2      2020-08-27 [1] CRAN (R 4.0.3)                      
#>  gt              0.2.2      2021-02-24 [1] Github (rstudio/gt@bae32f4)         
#>  gtable          0.3.0      2019-03-25 [1] CRAN (R 4.0.3)                      
#>  gtsummary     * 1.4.0.9002 2021-04-29 [1] Github (ddsjoberg/gtsummary@7959f76)
#>  highr           0.8        2019-03-20 [1] CRAN (R 4.0.3)                      
#>  htmltools       0.5.1.1    2021-01-22 [1] CRAN (R 4.0.3)                      
#>  knitr           1.31       2021-01-27 [1] CRAN (R 4.0.4)                      
#>  lattice         0.20-41    2020-04-02 [4] CRAN (R 4.0.0)                      
#>  lifecycle       1.0.0      2021-02-15 [1] CRAN (R 4.0.4)                      
#>  lubridate       1.7.9.2    2020-11-13 [1] CRAN (R 4.0.3)                      
#>  magrittr        2.0.1      2020-11-17 [1] CRAN (R 4.0.3)                      
#>  Matrix          1.3-2      2021-01-06 [4] CRAN (R 4.0.3)                      
#>  memoise         2.0.0      2021-01-26 [1] CRAN (R 4.0.4)                      
#>  munsell         0.5.0      2018-06-12 [1] CRAN (R 4.0.3)                      
#>  pillar          1.5.1      2021-03-05 [1] standard (@1.5.1)                   
#>  pkgbuild        1.2.0      2020-12-15 [1] CRAN (R 4.0.3)                      
#>  pkgconfig       2.0.3      2019-09-22 [1] CRAN (R 4.0.3)                      
#>  pkgload         1.2.0      2021-02-23 [1] CRAN (R 4.0.4)                      
#>  prettyunits     1.1.1      2020-01-24 [1] CRAN (R 4.0.3)                      
#>  processx        3.4.5      2020-11-30 [1] CRAN (R 4.0.3)                      
#>  ps              1.6.0      2021-02-28 [1] CRAN (R 4.0.4)                      
#>  purrr           0.3.4      2020-04-17 [1] CRAN (R 4.0.3)                      
#>  R6              2.5.0      2020-10-28 [1] CRAN (R 4.0.3)                      
#>  Rcpp            1.0.6      2021-01-15 [1] CRAN (R 4.0.3)                      
#>  remotes         2.2.0      2020-07-21 [1] CRAN (R 4.0.3)                      
#>  rlang           0.4.10     2020-12-30 [1] CRAN (R 4.0.3)                      
#>  rmarkdown       2.6        2020-12-14 [1] CRAN (R 4.0.3)                      
#>  rprojroot       2.0.2      2020-11-15 [1] CRAN (R 4.0.3)                      
#>  scales          1.1.1      2020-05-11 [1] CRAN (R 4.0.3)                      
#>  sessioninfo     1.1.1      2018-11-05 [1] CRAN (R 4.0.4)                      
#>  stringi         1.5.3      2020-09-09 [1] CRAN (R 4.0.3)                      
#>  stringr         1.4.0      2019-02-10 [1] CRAN (R 4.0.3)                      
#>  survival        3.2-10     2021-03-16 [4] CRAN (R 4.0.4)                      
#>  testthat        3.0.2      2021-02-14 [1] CRAN (R 4.0.4)                      
#>  tibble          3.1.0      2021-02-25 [1] CRAN (R 4.0.4)                      
#>  tidyr           1.1.3      2021-03-03 [1] standard (@1.1.3)                   
#>  tidyselect      1.1.0      2020-05-11 [1] CRAN (R 4.0.3)                      
#>  usethis         2.0.1      2021-02-10 [1] CRAN (R 4.0.4)                      
#>  utf8            1.1.4      2018-05-24 [1] CRAN (R 4.0.3)                      
#>  vctrs           0.3.6      2020-12-17 [1] CRAN (R 4.0.3)                      
#>  withr           2.4.1      2021-01-26 [1] CRAN (R 4.0.3)                      
#>  xfun            0.22       2021-03-11 [1] standard (@0.22)                    
#>  yaml            2.2.1      2020-02-01 [1] CRAN (R 4.0.3)                      
#> 
#> [1] /home/gw/R/x86_64-pc-linux-gnu-library/4.0
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Review by oranwutang — APPROVED** [review]

**Comment by oranwutang** [comment]
Houston, we have a problem!

I was thinking about the labels thing and this issue. I am afraid to tell you that as.numeric() removes labels from variables, so maybe just adding as.numeric() to the vars for wilcox.test() is not so good idea, it wil delete labels for any variable, wether is difftime or not...

``` r
dftv <- lubridate::as.difftime(rnorm(250, 2000, 200), units = "mins")
labelled::var_label(dftv) <- "Time Variable"
str(dftv)
#>  'difftime' num [1:250] 2044.35151353988 2152.98556145361 1884.59078120344 2334.26743254955 ...
#>  - attr(*, "units")= chr "mins"
#>  - attr(*, "label")= chr "Time Variable"
str(as.numeric(dftv))
#>  num [1:250] 2044 2153 1885 2334 1775 ...
```

<sup>Created on 2021-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't now what is the solution so far...

What do you think  @ddsjoberg ?

**Comment by ddsjoberg** [comment]
hello @oranwutang !

Is this a problem in `tbl_summar()`? The variable labels have already been extracted at that point?

**Comment by oranwutang** [comment]
Oh, now I see, probably won't be a problem then... I'll make a test to see if it works correctly

**Comment by oranwutang** [comment]
Hi Daniel!

Take a look at this, it seems that labels work fine except for the paired wilcoxon :s

``` r
library(gtsummary)
library(labelled)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

trial$difftimevar <- lubridate::as.difftime(rnorm(nrow(trial), 2000, 200), units = "mins")

var_label(trial$difftimevar) <- "Difftime Variable"

trial_paired <-
  trial %>%
  select(trt, difftimevar) %>%
  group_by(trt) %>%
  mutate(id = row_number()) %>%
  ungroup()

trial %>% 
  select(age, marker, difftimevar, trt) %>% 
  tbl_summary(by=trt) %>% 
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Drug A</strong>, N = 98</th>
<th style="text-align: left;"><strong>Drug B</strong>, N = 102</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">46 (37, 59)</td>
<td style="text-align: left;">48 (39, 56)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marker Level (ng/mL)</td>
<td style="text-align: left;">0.84 (0.24, 1.57)</td>
<td style="text-align: left;">0.52 (0.19, 1.20)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Difftime Variable</td>
<td style="text-align: left;">2,046 (1,876, 2,151)</td>
<td style="text-align: left;">2,042 (1,897, 2,146)</td>
</tr>
</tbody>
</table>

``` r

trial_paired %>% 
  select(difftimevar, trt) %>% 
  tbl_summary(by=trt) %>% 
  add_p() %>% 
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Drug A</strong>, N = 98</th>
<th style="text-align: left;"><strong>Drug B</strong>, N = 102</th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Difftime Variable</td>
<td style="text-align: left;">2,046 (1,876, 2,151)</td>
<td style="text-align: left;">2,042 (1,897, 2,146)</td>
<td style="text-align: left;">0.9</td>
</tr>
</tbody>
</table>

``` r

trial_paired %>%
  filter(!is.na(difftimevar)) %>%
  group_by(id) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  tbl_summary(by = trt, include = -id) %>%
  add_p(test = difftimevar ~ "paired.wilcox.test", group = id) %>% 
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Drug A</strong>, N = 98</th>
<th style="text-align: left;"><strong>Drug B</strong>, N = 98</th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">difftimevar</td>
<td style="text-align: left;">2,046 (1,876, 2,151)</td>
<td style="text-align: left;">2,045 (1,904, 2,148)</td>
<td style="text-align: left;">0.8</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
hey @oranwutang ! I think in that case, it is the `filter()` functions that are deleting the label attribute, not the paired test, right?

**Comment by oranwutang** [comment]
You are right, any subsetting or filter()ing applied to a variable will delete the label attribute...

``` r
library(gtsummary)
library(labelled)
library(dplyr)

trial$difftimevar <- lubridate::as.difftime(rnorm(nrow(trial), 2000, 200), units = "mins")

var_label(trial$difftimevar) <- "Difftime Variable"

trial_paired <-
  trial %>%
  select(trt, difftimevar) %>%
  group_by(trt) %>%
  mutate(id = row_number()) %>%
  ungroup()

trial_paired %>%
  # filter(!is.na(difftimevar)) %>%
  group_by(id) %>%
  # filter(n() == 2) %>%
  ungroup() %>%
  tbl_summary(by = trt, include = -id) %>%
  add_p(test = difftimevar ~ "paired.wilcox.test", group = id) %>% 
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Drug A</strong>, N = 98</th>
<th style="text-align: left;"><strong>Drug B</strong>, N = 102</th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Difftime Variable</td>
<td style="text-align: left;">1,977 (1,881, 2,116)</td>
<td style="text-align: left;">1,967 (1,875, 2,118)</td>
<td style="text-align: left;">&gt;0.9</td>
</tr>
</tbody>
</table>

``` r
str(trial_paired)
#> tibble [200 × 3] (S3: tbl_df/tbl/data.frame)
#>  $ trt        : chr [1:200] "Drug A" "Drug B" "Drug A" "Drug A" ...
#>   ..- attr(*, "label")= chr "Chemotherapy Treatment"
#>  $ difftimevar: 'difftime' num [1:200] 1943.25069841005 2208.38475210231 2052.45864237003 1866.09280895048 ...
#>   ..- attr(*, "units")= chr "mins"
#>   ..- attr(*, "label")= chr "Difftime Variable"
#>  $ id         : int [1:200] 1 1 2 3 4 2 5 6 7 3 ...
str(trial_paired[!is.na(trial_paired$difftimevar),])
#> tibble [200 × 3] (S3: tbl_df/tbl/data.frame)
#>  $ trt        : chr [1:200] "Drug A" "Drug B" "Drug A" "Drug A" ...
#>   ..- attr(*, "label")= chr "Chemotherapy Treatment"
#>  $ difftimevar: 'difftime' num [1:200] 1943.25069841005 2208.38475210231 2052.45864237003 1866.09280895048 ...
#>   ..- attr(*, "units")= chr "mins"
#>  $ id         : int [1:200] 1 1 2 3 4 2 5 6 7 3 ...
str(trial_paired %>% filter(!is.na(difftimevar)))
#> tibble [200 × 3] (S3: tbl_df/tbl/data.frame)
#>  $ trt        : chr [1:200] "Drug A" "Drug B" "Drug A" "Drug A" ...
#>   ..- attr(*, "label")= chr "Chemotherapy Treatment"
#>  $ difftimevar: 'difftime' num [1:200] 1943.25069841005 2208.38475210231 2052.45864237003 1866.09280895048 ...
#>   ..- attr(*, "units")= chr "mins"
#>  $ id         : int [1:200] 1 1 2 3 4 2 5 6 7 3 ...
```

<sup>Created on 2021-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by oranwutang** [comment]
[Here](https://github.com/tidyverse/dplyr/issues/5282) they say that this kind of problem is fixed with dplyr

**Comment by ddsjoberg** [comment]
I thought so too. I am not sure why the label isn't surviving 🤷🏼

**Comment by oranwutang** [comment]
It doesn't work for those labels assigned with {labelled}.

Effectively, it does works if labels are assigned using {haven}:

``` r
library(gtsummary)
library(haven)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

trial$difftimevar <- lubridate::as.difftime(rnorm(nrow(trial), 2000, 200), units = "mins")

trial$difftimevar <- haven::labelled(trial$difftimevar, label = "Difftime Variable")
str(trial$difftimevar)
#>  dbl+lbl [1:200] 1964.434, 1966.600, 1996.360, 2208.372, 2170.003, 1865.396...
#>  @ label: chr "Difftime Variable"

trial_paired <-
  trial %>%
  select(trt, difftimevar) %>%
  group_by(trt) %>%
  mutate(id = row_number()) %>%
  ungroup()

trial_paired %>%
  filter(!is.na(difftimevar)) %>%
  group_by(id) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  tbl_summary(by = trt, include = -id) %>%
  add_p(test = difftimevar ~ "paired.wilcox.test", group = id) %>% 
  as_kable()
#> ℹ Column(s) difftimevar are class haven_labelled. This is an intermediate datastructure not meant for analysis. Convert columns with `haven::as_factor()`, `labelled::to_factor()`, `labelled::unlabelled()`, and `unclass()`. haven_labelled value labels are ignored when columns are not converted. Failure to convert may have unintended consequences or result in error.
#> ● https://haven.tidyverse.org/articles/semantics.html
#> ●
#>   https://larmarange.github.io/labelled/articles/intro_labelled.html#unlabelled
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Drug A</strong>, N = 98</th>
<th style="text-align: left;"><strong>Drug B</strong>, N = 98</th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Difftime Variable</td>
<td style="text-align: left;">1,989 (1,890, 2,172)</td>
<td style="text-align: left;">2,026 (1,859, 2,142)</td>
<td style="text-align: left;">0.7</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Or if the labels are assigned using {Hmisc}:

``` r
library(gtsummary)
#> #BlackLivesMatter
library(Hmisc)
#> Loading required package: lattice
#> Loading required package: survival
#> Loading required package: Formula
#> Loading required package: ggplot2
#> 
#> Attaching package: 'Hmisc'
#> The following objects are masked from 'package:base':
#> 
#>     format.pval, units
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:Hmisc':
#> 
#>     src, summarize
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

trial$difftimevar <- lubridate::as.difftime(rnorm(nrow(trial), 2000, 200), units = "mins")

Hmisc::label(trial$difftimevar) <- "Diff Time Var"
str(trial$difftimevar)
#>  'labelled' num [1:200] 2180.90879547894 1954.74300155217 1895.59593412071 1980.23281931424 ...
#>  - attr(*, "units")= chr "mins"
#>  - attr(*, "label")= chr "Diff Time Var"

trial_paired <-
  trial %>%
  select(trt, difftimevar) %>%
  group_by(trt) %>%
  mutate(id = row_number()) %>%
  ungroup()



trial_paired %>%
  filter(!is.na(difftimevar)) %>%
  group_by(id) %>%
  filter(n() == 2) %>%
  ungroup() %>%
  tbl_summary(by = trt, include = -id) %>%
  add_p(test = difftimevar ~ "paired.wilcox.test", group = id) %>% 
  as_kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Drug A</strong>, N = 98</th>
<th style="text-align: left;"><strong>Drug B</strong>, N = 98</th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Diff Time Var</td>
<td style="text-align: left;">1,985 (1,897, 2,126)</td>
<td style="text-align: left;">2,009 (1,880, 2,148)</td>
<td style="text-align: left;">0.6</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
