### PR TITLE
 Fix in `tbl_uvregression()` for the `formula` argument

### LINKED ISSUE #1886: Bug Report: Variable defined as covariate in `tbl_uvregression` is reported in table output
Dear Mr. Sjoberg,
Dear gtsummary Team,

Hello,
I am using package gtsummary version 2.0.0 under R version 4.4.1 (Windows) and I noticed that when the variable, previously defined as a covariate in the formula argument of tbl_uvregression function, was reported in the table output. I also remembered it did not happen in previous versions and only noticed this issue after an update. 

``` r
#load packages
    
    library(tidyverse)
    library(gtsummary)
    
    #load data
    df <- read.table("https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.hungarian.data",sep = ",", header=TRUE)
    
    colnames(df)<-c("var_1",
                    "var_2",
                    "var_3",
                    "var_4",
                    "var_5",
                    "var_6",
                    "var_7",
                    "var_8",
                    "var_9",
                    "var_10",
                    "var_11",
                    "var_12",
                    "var_13",
                    "var_14")
    
    #univariate regression
    
    df <- df %>% mutate_at(vars(var_1,
                                var_3,
                                var_4,
                                var_5,
                                var_8,
                                var_10), as.numeric)
#> Warning: There were 3 warnings in `mutate()`.
#> The first warning was:
#> ℹ In argument: `var_4 = .Primitive("as.double")(var_4)`.
#> Caused by warning:
#> ! NAs introduzidos por coerção
#> ℹ Run `dplyr::last_dplyr_warnings()` to see the 2 remaining warnings.
    
    df %>%
        select(var_1,
               var_3,
               var_4,
               var_5,
               var_8,
               var_10) %>% 
        tbl_uvregression(
            method = lm,
            y = var_1,
            exponentiate = FALSE,
            hide_n = FALSE,
            formula = "{y} ~ {x} + var_3",
            pvalue_fun = function(x) {
                if_else(
                    is.na(x), 
                    NA_character_,
                    if_else(x < 0.001, format(x, digits = 2, scientific = TRUE), format(round(x, 3), scientific = F))
                )
            }) %>%
        add_q(method = "fdr") %>% 
        bold_p(q = TRUE, t = 0.05) %>% 
        sort_p(q = TRUE) %>% 
        modify_header(label ~ "Variables", p.value ~ "p", estimate ~ "Beta", conf.low ~ "CI 95%", q.value = "pcorr") %>% 
        as_flex_table()
```

<sup>Created on 2024-08-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
* Fix in `tbl_uvregression()` for the `formula` argument when it includes a hard-coded column name, e.g. `formula='{y} ~ {x} + grade'`. The hard-coded variable name is now removed from the `include` argument. This was a regression introduced in the v2.0.0 release. (#1886)

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #1886

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] Ensure all package dependencies are installed: `renv::install()`
- [ ] PR branch has pulled the most recent updates from master branch: `usethis::pr_merge_main()`
- [ ] If a bug was fixed, a unit test was added.
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

File: R/tbl_uvregression.R [hunk 1]
```diff
@@ -165,7 +165,11 @@ tbl_uvregression.data.frame <- function(data,
   # styler: off
   # remove any variables specified in arguments `x`/`y` from include
   include <- include |>
-    setdiff(tryCatch(stats::reformulate(c(x, y)) |> all.vars(), error = \(e) character()))
+    # remove the x/y variable from the list
+    setdiff(tryCatch(stats::reformulate(c(x, y)) |> all.vars(), error = \(e) character(0L))) |>
+    # remove any other columns listed in the formula
+    setdiff(tryCatch(glue::glue_data(.x = list(y = 1, x = 1), formula) |> stats::as.formula() |> all.vars(), error = \(e) character(0L)))
```
Comment (Melkiades) [inline R/tbl_uvregression.R:171]: The only issue here for me is that I could not include the other columns listed in the formula:
```r
trial |>
    select(age, grade, trt) |>
    tbl_uvregression(
        y = age,
        method = "lm",
        formula = "{y} ~ {x} + grade", include = "grade"
    )
```
It fixes the issue anyway ;)

**Comment by ddsjoberg** [comment]
Thanks @Melkiades !!
