### PR TITLE
adding test-style_sigfig and a line about bug fix #638 to NEWS.md

### LINKED ISSUE #638: style_sigfig() with rounding near digits threshold
```r
> style_sigfig(0.97, digits=1)
[1] "1.0"
```

### PR DESCRIPTION
**Pull request by zabore**
Added a unit test and a line to NEWS.md related to this bug fix.

### CODE REVIEW

File: tests/testthat/test-style_sigfig.R [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+test_that("correct rounding near thresholds", {
+
+  expect_equal(
+    c(1.0001, 1, 0.9999, 0.90000) %>% style_sigfig(digits = 1),
+    c("1", "1", "1", "0.9")
+  )
+
+  expect_false(
+    style_sigfig(0.97, digits = 1) == "0.1"
```
Comment (ddsjoberg) [inline tests/testthat/test-style_sigfig.R:12]: I am going to merge this now, but i think this line is meant to be 

`style_sigfig(0.97, digits = 1) == "1.0"`
