### PR TITLE
Fix when placing flextable footnote to multiple columns and rows

### LINKED ISSUE #2062: Bug Report: as_flex_table doesn't pass multi-column/row footnote coordinates correctly
I want to add footnotes throughout all levels of a variable and across a couple columns. Then I want to convert it to a flextable. I get an error at the `as_flex_table` stage. 

I think it's because during the creation of the flextable, (something that creates `flextable_calls`) it tries to create footnotes that reference at all permutations of `i` and `j`. However, `flextable` uses the pairwise combination of `i` and `j`:

`flextable::footnotes`
> Symbols are added to the cells designated by the selection i and j. If you use i = c(1,3) and j = c(2,5), then you will add the symbols (or the repeated symbol) to cells [1,2] and [3,5].

In addition to the example error below, I'm noticing that some other tables will only have flextable footnotes in alternating rows because of the way `i` and `j` are expanded. 

``` r
library(dplyr)
library(gtsummary)

trial %>% 
  tbl_summary(by = trt, 
              include = c(age,
                          stage,
                          grade)) %>% 
  modify_table_styling(columns = c(stat_1, stat_2),
                       rows = (variable %in% "grade") & (row_type == "level"),
                       footnote = "Cell-level foonotes here.") %>% 
  as_flex_table()
#> Error in data.frame(i = i, j = j): arguments imply differing number of rows: 3, 2
```

<sup>Created on 2024-11-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

When debugging `as_flex_table`
```
Browse[2]> flextable_calls$footnote
[[1]]
flextable::footnote(i = 1L, j = 2:3, value = flextable::as_paragraph("Median (IQR); n (%)"), 
    part = "header", ref_symbols = 1L)

[[2]]
flextable::footnote(i = 9:11, j = 2:3, value = flextable::as_paragraph("Cell-level foonotes here."), 
    part = "body", ref_symbols = 2L)
```

### PR DESCRIPTION
**Pull request by ddsjoberg**
**What changes are proposed in this pull request?**
* Bug fix when placing a footnote for flextable tables on multiple columns and rows. (#2062)

**If there is an GitHub issue associated with this pull request, please provide link.**
closes #2062 

@Melkiades before fully reviewing this PR, can you add a test or two more for different types of footnote placement to ensure they are correctly placed when there is one column and multiple rows, multiple columns and one row, and one mixed-type when the column/rows are contiguous? Thank you!

--------------------------------------------------------------------------------

Reviewer Checklist (if item does not apply, mark is as complete)

- [x] PR branch has pulled the most recent updates from main branch.
- [x] If a bug was fixed, a unit test was added.
- [x] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [x] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`
- [x] `usethis::use_spell_check()` runs with no spelling errors in documentation
- [x] **All** GitHub Action workflows pass with a :white_check_mark:

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# gtsummary (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Increment the version number using `usethis::use_version(which = "dev")` 
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge".

### CODE REVIEW

**Comment by Melkiades** [comment]
@ddsjoberg added a test, let me know if it was what you were looking for. Only place where I cannot add a footnote is the stubhead so far

**Review by Melkiades — APPROVED** [review]
Thanks Daniel for the fix. If It is what you need feel free to merge. From my side, I could not break it :D

**Comment by ddsjoberg** [comment]
Thanks @Melkiades ! Can you take a look into the failing CI/CD?

File: tests/testthat/test-as_flex_table.R [hunk 1]
```diff
@@ -271,6 +271,63 @@ test_that("as_flex_table passes table footnotes & footnote abbreviations correct
...
+  # testing one footnote passed to multiple columns and rows, addresses issue #2062
+  expect_silent(
+    my_tbl_summary |>
+      modify_footnote(stat_0 = NA) |>
+      modify_table_styling(
+        columns = c(label, stat_0),
+        rows = (variable %in% "trt") & (row_type == "level"),
+        footnote = "my footnote"
+      ) |>
+      as_flex_table()
```
Comment (ddsjoberg) [inline tests/testthat/test-as_flex_table.R:284]: @Melkiades could you add a test here for the values of the footnotes too? thank you!

Comment (Melkiades) [reply tests/testthat/test-as_flex_table.R]: done ;)

File: R/as_flex_table.R [hunk 2]
```diff
@@ -230,7 +230,17 @@ table_styling_to_flextable_calls <- function(x, ...) {
...
-      column_id = map(.data$location_ids, ~ getElement(.x, "column_id") |> unique())
+      column_id =
+        pmap(
+          list(.data$location_ids,
+               .data$tab_location,
+               .data$row_numbers),
+          \(location_ids, tab_location, row_numbers) {
+            col_ids <- getElement(location_ids, "column_id") |> unique()
+            if (tab_location == "body") col_ids <- rep(col_ids, length(row_numbers)) # styler: off
+            sort(col_ids)
```
Comment (ddsjoberg) [inline R/as_flex_table.R:241]: Hi @Melkiades , I was doing some final checks, and saw that we were not placing the footnote correctly. I added the `sort()` to get it right which changed the footnote placement from this
image

to

image

Is there a way to test that the placement of the footnote markers is where we expect in a flextable? 

Thanks!

File: tests/testthat/test-as_flex_table.R [hunk 3]
```diff
@@ -303,22 +303,22 @@ test_that("as_flex_table passes multiple table footnotes correctly", {
     modify_table_styling(
       columns = stat_1,
       rows = (variable %in% "grade") & (row_type == "level"),
-      footnote = "Cell-level foonotes here."
+      footnote = "my footnote"
```
Comment (Melkiades) [inline tests/testthat/test-as_flex_table.R:306]: why?

Comment (ddsjoberg) [reply tests/testthat/test-as_flex_table.R:306]: the bug appeared when we were assigning the same footnote to multiple locations. separate footnotes were assigned with separate calls to the flextable footnote function

File: R/as_flex_table.R (hunk 2 above)
Comment (ddsjoberg) [reply R/as_flex_table.R]: Thank you!!

File: tests/testthat/test-as_flex_table.R (hunk 3 above)
Comment (Melkiades) [reply tests/testthat/test-as_flex_table.R:306]: I see! thanks

**Comment by Melkiades** [comment]
@ddsjoberg let me know when going back to check it or add tests ;)

**Comment by ddsjoberg** [comment]
> @ddsjoberg let me know when going back to check it or add tests ;)

Thanks @Melkiades ! Can you re-check now? Also, if you know how to check the _location_ of the the footnote marker location for flextable, let's add those. I wasn't sure how to add

File: tests/testthat/test-as_flex_table.R [hunk 4]
```diff
@@ -1,5 +1,5 @@
 skip_on_cran()
-skip_if_not(is_pkg_installed("flextable"))
```
Comment (ddsjoberg) [inline tests/testthat/test-as_flex_table.R:2]: Can you change this back, because the `is_pkg_installed()` function also checks the min required version specified in the DESCRIPTION file?

**Comment by ddsjoberg** [comment]
Thank you @Melkiades !!
